version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest

    steps:
      - checkout
      - restore_cache:
          keys:
              - sfdx-version-42-local
      - run:
          name: Install Salesforce DX
          command: |
              openssl aes-256-cbc -k $KEY -in .circleci/server.key.enc -out .circleci/server.key -d
              export SFDX_USE_GENERIC_UNIX_KEYCHAIN=true
              export SFDX_DOMAIN_RETRY=300
              npm install sfdx-cli
              node_modules/sfdx-cli/bin/run --version
              node_modules/sfdx-cli/bin/run plugins --core
      - save_cache:
          key: sfdx-version-42-local
          paths:
              - node_modules
      - run:
          name: Authenticate DevHub
          command: |
              node_modules/sfdx-cli/bin/run force:auth:jwt:grant --clientid $CONSUMERKEY --jwtkeyfile .circleci/server.key --username $USERNAME --setdefaultdevhubusername -a HubOrg
      - run:
          name: Create Scratch Org
          command: |
              node_modules/sfdx-cli/bin/run force:org:create -v HubOrg -s -f config/project-scratch-def.json -a ciorg
      - run:
          name: Push Source
          command: |
             node_modules/sfdx-cli/bin/run force:source:push -u ciorg
      - run:
          name: Run Apex Tests
          command: |
              node_modules/sfdx-cli/bin/run force:apex:test:run -u ciorg -c -r human
      - run:
          name: Clean Up
          when: always
          command: |
              node_modules/sfdx-cli/bin/run force:org:delete -u ciorg -p
